packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

patchedDependencies:
  '@comark/nuxt@0.6.2': patches/@comark__nuxt@0.6.2.patch
  '@nuxt/content@3.16.0': patches/@nuxt__content@3.16.0.patch

  docus@5.12.3: patches/docus@5.12.3.patch

overrides:
  '@unhead/vue': 3.4.0
  unhead: 3.4.0
  '@happydesigns/course': 'file:../course/packages/course'
  '@nuxt/content': 3.16.0
  oxc-parser: 0.141.0
  unplugin: 3.3.0
  vue-component-meta: 3.3.8
  h3: "1.15.11"
