packages:
  - .

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: false
  esbuild: false
  sharp: false
  unrs-resolver: false
  vue-demi: false
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

patchedDependencies:
  '@nuxt/content@3.14.0': patches/@nuxt__content@3.14.0.patch
  docus@5.12.3: patches/docus@5.12.3.patch

overrides:
  h3: "1.15.11"
