import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { gzipSync } from 'node:zlib'
import { pathToFileURL } from 'node:url'
import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import source from '../../src/brand/brand.studio.json' with { type: 'json' }

async function choose(page: import('@playwright/test').Page, name: string, option: string) {
  await page.getByRole('combobox', { name, exact: true }).click()
  await page.getByRole('option', { name: option, exact: true }).click()
}

const draft = (page: import('@playwright/test').Page) => page.frameLocator('iframe[title="Draft brand preview"]')

async function projectAction(page: import('@playwright/test').Page, action: string) {
  await page.getByRole('button', { name: 'Brand actions', exact: true }).click()
  await page.getByRole('menuitem', { name: action === 'New brand' ? 'Create new brand' : action, exact: true }).click()
  if (action === 'New brand') await nameBrand(page)
}
async function nameBrand(page: import('@playwright/test').Page) {
  const dialog = page.getByRole('dialog', { name: 'Create brand', exact: true })
  await dialog.getByLabel('New brand name', { exact: true }).fill('New brand')
  await dialog.getByRole('button', { name: 'Create brand', exact: true }).click()
}
async function openPanel(page: import('@playwright/test').Page, panel: string) {
  if (!await page.getByLabel('Brand settings').isVisible()) await page.getByRole('button', { name: 'Customize', exact: true }).click()
  const trigger = page.getByRole('button', { name: panel, exact: true })
  if (await trigger.getAttribute('aria-expanded') !== 'true') await trigger.click()
}
async function setCompare(page: import('@playwright/test').Page, checked: boolean) {
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Compare applied brand', exact: true }).setChecked(checked)
  await page.keyboard.press('Escape')
}
async function setMode(page: import('@playwright/test').Page, mode: string) {
  await choose(page, 'Color mode', mode)
}
async function lesson(page: import('@playwright/test').Page) {
  if (await draft(page).getByRole('link', { name: 'Explore the course' }).isVisible()) await draft(page).getByRole('link', { name: 'Explore the course' }).click()
  await draft(page).getByRole('link', { name: 'Start course', exact: true }).click()
}

test('viewport presets preserve CSS dimensions, rotate and share custom sizes', async ({ page }) => {
  await page.goto('/studio?browse=true&compare=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Preview width', exact: true }).click()
  await page.screenshot({ path: 'test-results/studio-viewport-options.png', animations: 'disabled' })
  await page.keyboard.press('Escape')
  await choose(page, 'Preview width', 'Desktop · 1440 × 900')
  const viewport = () => page.locator('iframe[title="Draft brand preview"]').evaluate((frame: HTMLIFrameElement) => ({ width: frame.contentWindow!.innerWidth, height: frame.contentWindow!.innerHeight }))
  await expect.poll(viewport).toEqual({ width: 1440, height: 900 })
  await expect(page.locator('iframe[title="Original brand preview"]')).toHaveCSS('width', '1440px')
  await page.getByRole('button', { name: 'Rotate viewport' }).click()
  await expect.poll(viewport).toEqual({ width: 900, height: 1440 })
  await page.getByRole('spinbutton', { name: 'Viewport width', exact: true }).fill('820')
  await page.getByRole('spinbutton', { name: 'Viewport width', exact: true }).press('Tab')
  await expect.poll(viewport).toEqual({ width: 820, height: 1440 })
  await expect(page).toHaveURL(/width=820/)
  await page.reload()
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await expect.poll(viewport).toEqual({ width: 820, height: 1440 })
  await choose(page, 'Preview width', 'Tablet · 768 × 1024')
  await expect(draft(page).locator('.component-gallery')).toHaveCSS('padding-bottom', '14px')
  await page.screenshot({ path: 'test-results/studio-viewport-tablet.png', animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await choose(page, 'Preview width', 'Mobile S · 320 × 568')
  await page.keyboard.press('Escape')
  await expect.poll(viewport).toEqual({ width: 320, height: 568 })
  await expect(draft(page).locator('.component-gallery')).toHaveCSS('padding-bottom', '12px')
  await page.screenshot({ path: 'test-results/studio-viewport-mobile.png', animations: 'disabled' })
})

test('saved brand management renames duplicates and deletes only confirmed local copies', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await projectAction(page, 'New brand')
  await projectAction(page, 'Manage brands')
  const manager = page.getByRole('dialog', { name: 'Manage brands', exact: true })
  await manager.getByRole('button', { name: 'Rename', exact: true }).click()
  await manager.getByLabel('Rename brand', { exact: true }).fill('Managed brand')
  await manager.getByRole('button', { name: 'Save name' }).click()
  await expect(manager.locator('li')).toContainText('Managed brand')
  await manager.getByRole('button', { name: 'Duplicate', exact: true }).click()
  const duplicate = page.getByRole('dialog', { name: 'Duplicate brand', exact: true })
  await duplicate.getByRole('button', { name: 'Create brand', exact: true }).click()
  await projectAction(page, 'Manage brands')
  await expect(manager.locator('li')).toHaveCount(2)
  await manager.getByLabel('Search saved brands').fill('Managed brand copy')
  await expect(manager.locator('li')).toHaveCount(1)
  await manager.getByRole('button', { name: 'Delete local copy' }).click()
  await manager.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(manager.locator('li')).toHaveCount(1)
  await manager.getByRole('button', { name: 'Delete local copy' }).click()
  await manager.getByRole('button', { name: 'Delete local copy' }).click()
  await expect(manager.getByText('No matching brands.')).toBeVisible()
  await manager.getByLabel('Search saved brands').fill('')
  await expect(manager.locator('li')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/studio-manage-brands.png', animations: 'disabled' })
  await page.reload()
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await projectAction(page, 'Manage brands')
  await expect(manager.locator('li')).toHaveCount(1)
  await expect(manager.locator('li')).toContainText('Managed brand')
})

test('brand editing isolates previews and supports undo, redo, reset and real states', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await setCompare(page, true)
  const original = page.frameLocator('iframe[title="Original brand preview"]')
  await expect(original.getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('A considered revision')
  await page.getByLabel(/^Brand name/).press('Tab')
  await expect(page.locator('.studio-project-name').filter({ hasText: 'A considered revision' })).toBeVisible()
  await page.getByRole('button', { name: 'Undo change' }).click()
  await expect(page.locator('.studio-project-name').filter({ hasText: source.theme.label })).toBeVisible()
  await page.getByRole('button', { name: 'Redo change' }).click()
  await expect(page.locator('.studio-project-name').filter({ hasText: 'A considered revision' })).toBeVisible()
  await page.getByRole('button', { name: 'Appearance', exact: true }).click()
  await page.getByLabel(/^Page background/).fill('#e0f2fe')
  await page.getByLabel(/^Page background/).press('Tab')
  await expect(draft(page).locator('body')).toHaveCSS('background-color', 'rgb(224, 242, 254)')
  await expect(original.locator('body')).not.toHaveCSS('background-color', 'rgb(224, 242, 254)')
  await setMode(page, 'Dark')
  await expect(draft(page).locator('html')).toHaveClass(/dark/)
  await expect(original.locator('html')).toHaveClass(/dark/)
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await choose(page, 'Preview state', 'Validation error')
  await page.keyboard.press('Escape')
  await expect(draft(page).getByText('Enter a valid email address.')).toBeVisible()
  await draft(page).getByRole('button', { name: 'Preview dialog' }).click()
  await expect(draft(page).getByRole('dialog')).toBeVisible()
  await expect(original.getByRole('dialog')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/studio-compare-dark.png', fullPage: true, animations: 'disabled' })
  await draft(page).getByRole('button', { name: 'Done', exact: true }).click()
  await projectAction(page, 'Reset draft')
  await expect(page.getByRole('button', { name: 'Redo change' })).toBeDisabled()
})

test('source export preserves the complete brand and invalid imports leave it intact', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await page.getByLabel('Open brand document').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"version":2}') })
  await expect(page.getByRole('alert')).toBeVisible()
  await projectAction(page, 'Review changes')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download source' }).click()
  const download = await downloadPromise
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual(source)
  const archivePromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download new project' }).click()
  const archive = await archivePromise
  expect(archive.suggestedFilename()).toMatch(/\.zip$/)
  await archive.saveAs('test-results/exported-brand.zip')
})

test('new brands clear inherited styles and keep a recoverable local draft', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await projectAction(page, 'New brand')
  await openPanel(page, 'Brand')
  await expect(page.locator('.studio-project-name').filter({ hasText: 'New brand' })).toBeVisible()
  await expect(draft(page).locator('body')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(draft(page).getByRole('img', { name: /happydesigns/ })).toHaveCount(0)
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('My saved draft')
  await page.getByLabel(/^Brand name/).press('Tab')
  page.on('dialog', dialog => dialog.accept())
  await page.reload()
  await page.getByRole('button', { name: 'Restore draft' }).click()
  await expect(page.locator('.studio-project-name').filter({ hasText: 'My saved draft' })).toBeVisible()
  await choose(page, 'Template', 'Landing')
  await expect(draft(page).getByText('Make it your own.', { exact: true })).toBeVisible()
  await choose(page, 'Template', 'Docs')
  await expect(draft(page).getByRole('heading', { name: 'Brand guide', exact: true })).toBeVisible({ timeout: 30_000 })
})

// Independent iframe UApp regions have the same upstream notification label.
test('studio shell and component scene have no new semantic accessibility violations', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await page.screenshot({ path: 'test-results/studio-desktop.png', fullPage: true, animations: 'disabled' })
  const result = await new AxeBuilder({ page }).disableRules(['landmark-unique']).analyze()
  expect(result.violations).toEqual([])
  await setMode(page, 'Dark')
  await expect(draft(page).locator('html')).toHaveCSS('color-scheme', 'dark')
  const dark = await new AxeBuilder({ page }).disableRules(['landmark-unique']).analyze()
  expect(dark.violations).toEqual([])
})

test('@mobile studio keeps controls and preview inside the viewport', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await openPanel(page, 'Palette')
  await expect(page.getByRole('combobox', { name: 'primary', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/studio-mobile.png', fullPage: true, animations: 'disabled' })
})

for (const viewport of [{ width: 1716, height: 1300 }, { width: 1440, height: 900 }, { width: 1024, height: 600 }, { width: 768, height: 600 }]) {
  test(`preview owns scrolling at ${viewport.width} × ${viewport.height}`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await page.goto('/studio?browse=true')
    await expect(draft(page).getByRole('heading', { name: 'Notifications' })).toBeVisible()
    const geometry = await page.evaluate(() => {
      const frame = document.querySelector<HTMLIFrameElement>('iframe')!
      const rect = frame.getBoundingClientRect()
      const doc = frame.contentDocument!
      const cards = [...doc.querySelectorAll('.example-card')].map(card => card.getBoundingClientRect())
      return {
        outerHeight: document.documentElement.scrollHeight,
        outerWidth: document.documentElement.scrollWidth,
        previewHeight: rect.height,
        frameWidth: frame.clientWidth,
        contentWidth: doc.documentElement.scrollWidth,
        contentHeight: doc.documentElement.scrollHeight,
        visibleCards: cards.filter(card => card.top < rect.height && card.bottom > 0).length,
        columns: new Set(cards.map(card => Math.round(card.left))).size
      }
    })
    expect(geometry.outerHeight).toBe(viewport.height)
    expect(geometry.outerWidth).toBe(viewport.width)
    expect(geometry.previewHeight).toBeGreaterThan(viewport.height * 0.68)
    expect(geometry.contentWidth).toBeLessThanOrEqual(geometry.frameWidth)
    expect(geometry.contentHeight).toBeGreaterThan(geometry.previewHeight)
    expect(geometry.visibleCards).toBeGreaterThanOrEqual(viewport.width >= 1440 ? 9 : 4)
    expect(geometry.columns).toBe(viewport.width >= 1440 ? 4 : viewport.width >= 1024 ? 3 : 2)
    const box = await page.locator('iframe').boundingBox()
    await page.mouse.move(box!.x + 30, box!.y + 100)
    await page.mouse.wheel(0, 650)
    await expect.poll(() => draft(page).locator('html').evaluate(() => window.scrollY)).toBeGreaterThan(0)
    expect(await page.evaluate(() => window.scrollY)).toBe(0)
    await expect(page.getByRole('button', { name: 'Customize', exact: true })).toBeInViewport()
    await openPanel(page, 'Palette')
    await expect(page.getByLabel('Brand settings')).toBeInViewport()
    await page.getByRole('button', { name: 'Close settings' }).click()
    await expect(page.getByLabel('Brand settings')).toHaveCount(0)
    await setMode(page, 'Dark')
    await expect(draft(page).locator('html')).toHaveCSS('color-scheme', 'dark')
    await draft(page).locator('html').evaluate(() => window.scrollTo(0, 0))
    await expect.poll(() => draft(page).locator('html').evaluate(() => window.scrollY)).toBe(0)
    await page.screenshot({ path: `test-results/studio-${viewport.width}-${viewport.height}.png`, animations: 'disabled' })
  })
}

test('@mobile preview and settings remain independently reachable without page scrolling', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('heading', { name: 'Recent activity' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBe(await page.evaluate(() => innerHeight))
  await openPanel(page, 'Palette')
  await expect(page.getByRole('combobox', { name: 'primary', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close settings' }).click()
  await expect(page.getByLabel('Brand settings')).toHaveCount(0)
  await draft(page).getByRole('textbox', { name: 'Search', exact: true }).fill('Jamie')
  await expect(draft(page).getByRole('button', { name: 'Jamie Chen' })).toHaveCount(1)
  await expect(draft(page).getByRole('button', { name: 'Alex Morgan' })).toHaveCount(0)
  await setCompare(page, true)
  for (const frame of await page.locator('iframe').all()) await expect(frame).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBe(await page.evaluate(() => innerHeight))
  await setCompare(page, false)
  await page.screenshot({ path: 'test-results/studio-mobile-browse.png', animations: 'disabled' })
})

test('capability template shares real course navigation and isolates learner state', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await choose(page, 'Template', 'Academy')
  await expect(draft(page).getByRole('heading', { name: 'Build your first interface' })).toBeVisible()
  await page.screenshot({ path: 'test-results/studio-academy-home.png', animations: 'disabled' })
  expect((await new AxeBuilder({ page }).disableRules(['landmark-unique']).analyze()).violations).toEqual([])
  await draft(page).getByRole('link', { name: 'Explore the course' }).click()
  await expect(page).toHaveURL(/page=overview/)
  await expect(draft(page).getByRole('heading', { name: 'Build an accessible page', exact: true })).toBeVisible()
  await setCompare(page, true)
  const original = page.frameLocator('iframe[title="Original brand preview"]')
  await lesson(page)
  await expect(draft(page).getByRole('heading', { name: 'Start with a clear hierarchy', exact: true })).toBeVisible()
  await expect(original.getByRole('heading', { name: 'Start with a clear hierarchy', exact: true })).toBeVisible()
  const checkpoint = draft(page).getByRole('checkbox').first()
  await checkpoint.check()
  await expect(checkpoint).toBeChecked()
  await expect(original.getByRole('checkbox').first()).not.toBeChecked()
  await setMode(page, 'Dark')
  await expect(checkpoint).toBeChecked()
  await expect(draft(page).locator('html')).toHaveClass(/dark/)
  expect(await page.evaluate(() => Object.keys(localStorage).filter(key => key.includes('academy')).length)).toBe(0)
  await page.screenshot({ path: 'test-results/studio-academy-compare.png', animations: 'disabled' })
})

test('@mobile capability template stays usable within the studio viewport', async ({ page }) => {
  await page.goto('/studio?browse=true&view=academy')
  await expect(draft(page).getByRole('heading', { name: 'Build your first interface' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await draft(page).locator('html').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/studio-academy-mobile.png', animations: 'disabled' })
  await lesson(page)
  await expect(draft(page).getByRole('heading', { name: 'Start with a clear hierarchy', exact: true })).toBeVisible()
  expect(await draft(page).locator('html').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})

test('production loads capability scene only when selected', async ({ page }, testInfo) => {
  test.skip(process.env.STUDIO_PRODUCTION !== 'true', 'Run against the production build with STUDIO_PRODUCTION=true.')
  const client = resolve('docs/node_modules/.cache/nuxt/.nuxt/dist/client')
  const manifest = (await import(pathToFileURL(resolve(client, '../server/client.manifest.mjs')).href)).default as Record<string, { file: string }>
  const scene = Object.entries(manifest).find(([key]) => key.includes('CourseAcademyPreview.vue'))?.[1]
  expect(scene, 'The capability must have its own production chunk').toBeTruthy()
  const requests: string[] = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  expect(requests.some(url => url.endsWith(scene!.file))).toBe(false)
  const before = requests.length
  const start = Date.now()
  await choose(page, 'Template', 'Academy')
  await expect(draft(page).getByRole('heading', { name: 'Build your first interface' })).toBeVisible()
  expect(requests.some(url => url.endsWith(scene!.file))).toBe(true)
  const module = readFileSync(resolve(client, '_nuxt', scene!.file))
  const report = { sceneChunk: scene!.file, sceneBytes: module.length, sceneGzipBytes: gzipSync(module).length, selectionToVisibleMs: Date.now() - start, initialRequestCount: before, additionalRequests: requests.slice(before) }
  const reportPath = testInfo.outputPath('academy-loading.json')
  writeFileSync(reportPath, JSON.stringify(report, null, 2))
  await testInfo.attach('academy-loading.json', { path: reportPath, contentType: 'application/json' })
})

test('feedback validates real fields and template controls stay relevant', async ({ page }) => {
  await page.goto('/studio?browse=true')
  const frame = draft(page)
  await frame.getByRole('button', { name: 'Send feedback', exact: true }).click()
  await expect(frame.getByText('Enter a title.', { exact: true })).toBeVisible()
  await frame.getByRole('textbox', { name: /^Title/ }).fill('Keyboard focus')
  await frame.getByRole('textbox', { name: /^Description/ }).fill('The save button needs a visible focus ring.')
  await frame.getByRole('button', { name: 'Send feedback', exact: true }).click()
  await expect(frame.getByRole('status').filter({ hasText: 'Feedback validated.' })).toBeVisible()
  await choose(page, 'Template', 'Landing')
  await expect(page.getByRole('combobox', { name: 'Preview state' })).toHaveCount(0)
  await frame.getByRole('button', { name: 'Create a project', exact: true }).click()
  await frame.getByRole('textbox', { name: 'Project name', exact: true }).fill('Website redesign')
  await frame.getByRole('button', { name: 'Create project', exact: true }).click()
  await expect(frame.getByText('Project created', { exact: true })).toBeVisible()
})

test('@mobile header keeps project actions secondary and keyboard accessible', async ({ page }) => {
  await page.goto('/studio?browse=true&view=academy')
  await expect(draft(page).getByRole('heading', { name: 'Build your first interface' })).toBeVisible()
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 })
    const header = page.locator('.studio-header')
    expect((await header.boundingBox())!.height).toBeLessThanOrEqual(56)
    expect(await draft(page).locator('html').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByRole('button', { name: 'Export', exact: true })).toBeHidden()
    await expect(page.getByRole('button', { name: 'New brand', exact: true })).toBeHidden()
  }
  await page.screenshot({ path: 'test-results/studio-academy-mobile-header.png', animations: 'disabled' })
  const actions = page.getByRole('button', { name: 'Brand actions' })
  await actions.focus()
  await page.keyboard.press('Enter')
  await page.getByRole('menuitem', { name: 'Review changes', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog', { name: /Review changes|Download brand/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await actions.click()
  const fileChooser = page.waitForEvent('filechooser')
  await page.getByRole('menuitem', { name: 'Open brand', exact: true }).click()
  await fileChooser
  await actions.click()
  await page.getByRole('menuitem', { name: 'Create new brand', exact: true }).click()
  await nameBrand(page)
  await expect(page.locator('.studio-project-name').filter({ hasText: 'New brand' })).toBeVisible()
  await choose(page, 'Template', 'Components')
  await page.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
})

test('projects survive switching and export preserves the comparison baseline', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Project A')
  await page.getByLabel(/^Brand name/).press('Tab')
  await expect(page.getByText('Saved in this browser', { exact: false })).toBeVisible()
  await projectAction(page, 'Review changes')
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download source' }).click()
  await downloading
  await expect(page.getByRole('button', { name: 'Download source', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await projectAction(page, 'New brand')
  await openPanel(page, 'Brand')
  await expect(page.getByRole('dialog', { name: 'Replace this draft?' })).toHaveCount(0)
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Project B')
  await page.getByLabel(/^Brand name/).press('Tab')
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('option', { name: 'Project A', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Replace this draft?' })).toHaveCount(0)
  await expect(page.locator('.studio-project-name').filter({ hasText: 'Project A' })).toBeVisible()
  await page.getByRole('button', { name: 'Brand actions', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Reset draft', exact: true })).toBeEnabled()
  await page.keyboard.press('Escape')
  await page.reload()
  await page.getByRole('button', { name: 'Restore draft' }).click()
  await expect(page.locator('.studio-project-name').filter({ hasText: 'Project A' })).toBeVisible()
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await expect(page.getByRole('option', { name: 'Project B', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await projectAction(page, 'Reset draft')
  await expect(page.locator('.studio-project-name').filter({ hasText: source.theme.label })).toBeVisible()
})

test('view URLs restore safe navigation state without including draft data', async ({ page }) => {
  await page.goto('/studio?browse=true&view=academy&page=lesson&mode=dark&compare=true')
  await expect(draft(page).getByRole('heading', { name: 'Start with a clear hierarchy', exact: true })).toBeVisible()
  await expect(draft(page).locator('html')).toHaveClass(/dark/)
  await expect(page.locator('iframe')).toHaveCount(2)
  await draft(page).getByRole('link', { name: /academy/i }).first().click()
  await expect(page).toHaveURL(/page=home/)
  await page.reload()
  await expect(draft(page).getByRole('heading', { name: 'Build your first interface' })).toBeVisible()
  expect(page.url()).not.toContain('brand.studio')
  await page.goto('/studio?browse=true&view=invalid&page=bad&mode=invalid')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await expect(draft(page).locator('html')).toHaveClass(/light/)
})

test('brand picker isolates brands, preserves drafts and protects the Nuxt UI baseline', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Studio library draft')
  await page.getByLabel(/^Brand name/).press('Tab')
  const shellColor = await page.locator('.studio-shell').evaluate(element => getComputedStyle(element).backgroundColor)
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('option', { name: 'Nuxt UI', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('Nuxt UI')
  await expect(page.getByLabel('Brand settings')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Create brand', exact: true })).toBeVisible()
  await expect(page.locator('.studio-shell')).toHaveCSS('background-color', shellColor)
  await page.getByRole('button', { name: 'Brand picker' }).click()
  await page.getByLabel('Search brands', { exact: true }).fill('library')
  await page.getByRole('option', { name: 'Studio library draft', exact: true }).click()
  await expect(page.getByLabel(/^Brand name/)).toHaveValue('Studio library draft')
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('option', { name: 'Nuxt UI', exact: true }).click()
  await page.getByRole('button', { name: 'Create brand', exact: true }).click()
  await nameBrand(page)
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Independent brand')
  await page.getByLabel(/^Brand name/).press('Tab')
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('option', { name: 'Nuxt UI', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('Nuxt UI')
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('option', { name: 'Independent brand', exact: true }).click()
  await expect(page.getByLabel(/^Brand name/)).toHaveValue('Independent brand')
  await page.getByRole('button', { name: 'Brand picker' }).click()
  await expect(page.getByRole('option', { name: 'Create new brand', exact: true })).toHaveCount(0)
  await expect(page.getByRole('option', { name: 'Download', exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/studio-brand-library.png', animations: 'disabled' })
})

test('visual authoring validates fields and previews palette, fonts and contrast', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await openPanel(page, 'Palette')
  await page.getByRole('textbox', { name: 'Base color', exact: true }).fill('#d946ef')
  await page.getByRole('textbox', { name: 'Base color', exact: true }).press('Tab')
  await page.getByRole('button', { name: 'Add palette', exact: true }).click()
  await choose(page, 'primary', 'accent')
  await page.getByRole('button', { name: 'accent', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'accent 500', exact: true })).toHaveValue('#d946ef')
  await page.getByRole('button', { name: 'Choose color for accent 500' }).click()
  await expect(page.getByRole('button', { name: 'Apply color', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Apply color', exact: true }).click()
  await page.screenshot({ path: 'test-results/studio-palette-editor.png', animations: 'disabled' })
  await openPanel(page, 'Typography')
  await choose(page, 'sans preset', 'System serif')
  await expect(page.getByText('The quick brown fox. 0123456789').first()).toHaveCSS('font-family', 'Georgia, serif')
  await openPanel(page, 'Appearance')
  await page.getByRole('button', { name: 'Round', exact: true }).click()
  await expect(page.getByLabel('Corner radius', { exact: true })).toHaveValue('0.5rem')
  const background = page.getByRole('textbox', { name: 'Page background', exact: true })
  await background.fill('not-a-color')
  await background.press('Tab')
  await expect(page.getByText('Enter a valid CSS color.', { exact: true })).toBeVisible()
  await expect(background).toHaveAttribute('aria-invalid', 'true')
  await background.fill('#ffffff')
  await background.press('Tab')
  await expect(page.getByText('Enter a valid CSS color.', { exact: true })).toHaveCount(0)
  const text = page.getByRole('textbox', { name: 'Body text', exact: true })
  await text.fill('#eeeeee')
  await text.press('Tab')
  await expect(page.getByText(/below 4.5:1 for normal text/)).toBeVisible()
})

test('storage failures protect edits until an export is downloaded', async ({ page }) => {
  await page.addInitScript(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key.startsWith('id-studio:')) throw new DOMException('Quota exceeded', 'QuotaExceededError')
      return original.call(this, key, value)
    }
  })
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Keep these edits')
  await page.getByLabel(/^Brand name/).press('Tab')
  await expect(page.getByText('Local draft storage is unavailable. Export your source before leaving.')).toBeVisible()
  await projectAction(page, 'New brand')
  await expect(page.getByRole('dialog', { name: 'Replace this draft?' })).toBeVisible()
  await page.getByRole('button', { name: 'Keep editing', exact: true }).click()
  await projectAction(page, 'Review changes')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download source', exact: true }).click()
  await download
  await page.keyboard.press('Escape')
  await projectAction(page, 'New brand')
  await openPanel(page, 'Brand')
  await expect(page.locator('.studio-project-name').filter({ hasText: 'New brand' })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Replace this draft?' })).toHaveCount(0)
})

test('creating a brand requires a distinct name and browsing creates no saved copies', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  const savedCount = () => page.evaluate(() => Object.keys(localStorage).filter(key => key.startsWith('id-studio:project:2:')).length)
  expect(await savedCount()).toBe(0)
  await page.getByRole('button', { name: 'Brand actions' }).click()
  await page.getByRole('menuitem', { name: 'Create new brand', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Create brand', exact: true })
  await expect(dialog.getByRole('button', { name: 'Create brand', exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await savedCount()).toBe(0)
  await page.getByRole('button', { name: 'Brand picker' }).click()
  await page.getByRole('option', { name: 'Nuxt UI', exact: true }).click()
  expect(await savedCount()).toBe(0)
  await page.getByRole('button', { name: 'Create brand', exact: true }).click()
  await dialog.getByLabel('New brand name', { exact: true }).fill('Nuxt UI')
  await dialog.getByRole('button', { name: 'Create brand', exact: true }).click()
  await expect(dialog.getByText('A brand with this name already exists. Choose a different name.')).toBeVisible()
  await dialog.getByLabel('New brand name', { exact: true }).fill('A named brand')
  await dialog.getByRole('button', { name: 'Create brand', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('A named brand')
  expect(await savedCount()).toBe(1)
  await page.evaluate((document) => {
    document.theme.label = 'New brand'
    for (const [id, updatedAt] of [['old-a', 1700000000000], ['old-b', 1700003600000]] as const) {
      localStorage.setItem(`id-studio:project:2:${id}`, JSON.stringify({ id, baseline: document, draft: document, updatedAt }))
    }
  }, structuredClone(source))
  await page.reload()
  await expect(draft(page).getByRole('heading', { name: 'Component examples' })).toBeVisible()
  await page.getByRole('button', { name: 'Brand picker' }).click()
  const legacy = page.getByRole('option', { name: /^New brand / })
  await expect(legacy).toHaveCount(2)
  expect(new Set(await legacy.allTextContents()).size).toBe(2)
  await page.screenshot({ path: 'test-results/studio-named-brands.png', animations: 'disabled' })
})
