import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { gzipSync } from 'node:zlib'
import { pathToFileURL } from 'node:url'
import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'
import source from '../../src/brand/brand.studio.json' with { type: 'json' }

import { brandActions, choose, closeEditor, openPanel, previewSettings, setCompare, setMode, surfaces } from './studio-helpers'

const draft = (page: import('@playwright/test').Page) => page.frameLocator('iframe[title="Draft brand preview"]')

async function projectAction(page: import('@playwright/test').Page, action: string) {
  if (['Review changes', 'Download'].includes(action)) {
    await closeEditor(page)
    await page.getByRole('button', { name: 'Export', exact: true }).click()
    await page.getByRole('dialog', { name: 'Export brand', exact: true }).getByRole('tab', { name: action === 'Download' ? 'Export' : 'Changes', exact: true }).click()
    return
  }
  await brandActions(page)
  await page.getByRole('menuitem', { name: action === 'New brand' ? 'Create new brand' : action === 'Reset draft' ? 'Reset appearance…' : action, exact: true }).click()
  if (action === 'New brand') await nameBrand(page)
  if (action === 'Reset draft') await page.getByRole('dialog', { name: 'Reset appearance?' }).getByRole('button', { name: 'Reset appearance', exact: true }).click()
}
async function nameBrand(page: import('@playwright/test').Page) {
  const dialog = page.getByRole('dialog', { name: 'Create brand', exact: true })
  await dialog.getByLabel('New brand name', { exact: true }).fill('New brand')
  await dialog.getByRole('button', { name: 'Create brand', exact: true }).click()
  await expect(dialog).toHaveCount(0)
}
async function lesson(page: import('@playwright/test').Page) {
  await expect(draft(page).locator('html')).toHaveAttribute('data-id-preview', 'ready', { timeout: 30000 })
  if (await draft(page).getByRole('heading', { name: 'Courses', exact: true }).isVisible()) await draft(page).getByRole('link', { name: /RAP120 - Build SAP Fiori Apps/ }).click()
  await draft(page).getByRole('link', { name: 'Start course', exact: true }).click()
}

test('reload shows the saved brand before the preview is ready without a download counter', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await projectAction(page, 'New brand')
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Reload brand')
  await page.getByLabel(/^Brand name/).press('Tab')
  let release!: () => void
  const gate = new Promise<void>((resolve) => {
    release = resolve
  })
  await page.route('**/studio/preview?**', async (route) => {
    await gate
    await route.continue()
  })
  try {
    await page.reload({ waitUntil: 'domcontentloaded' })
    await expect(page.getByRole('button', { name: 'Brand picker', exact: true })).toHaveText('Reload brand')
    await expect(page.locator('.studio-review')).toContainText('Export')
    await expect(page.getByText('Loading preview', { exact: true })).toHaveCount(1)
    const before = await page.locator('.studio-workspace').boundingBox()
    release()
    await expect(page.getByText('Loading preview', { exact: true })).toHaveCount(0, { timeout: 30000 })
    await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
    expect(await page.locator('.studio-workspace').boundingBox()).toEqual(before)
  } finally { release() }
})

test('viewport presets preserve CSS dimensions, rotate and share custom sizes', async ({ page }) => {
  await page.goto('/studio?browse=true&compare=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await expect(page.locator('.viewport-handle')).toHaveCount(0)
  await choose(page, 'Preview width', 'Desktop')
  const viewport = () => page.locator('iframe[title="Draft brand preview"]').evaluate((frame: HTMLIFrameElement) => ({ width: frame.contentWindow!.innerWidth, height: frame.contentWindow!.innerHeight }))
  await expect.poll(viewport).toEqual({ width: 1440, height: 900 })
  await page.getByRole('button', { name: 'Rotate viewport' }).click()
  await expect.poll(viewport).toEqual({ width: 900, height: 1440 })
  await page.getByRole('spinbutton', { name: 'Viewport width', exact: true }).fill('820')
  await page.getByRole('spinbutton', { name: 'Viewport width', exact: true }).press('Tab')
  await expect.poll(viewport).toEqual({ width: 820, height: 1440 })
  await page.keyboard.press('Escape')
  const corner = page.locator('.studio-frame-wrap').last().getByRole('button', { name: 'Resize viewport both', exact: true })
  await corner.press('Shift+ArrowUp')
  await expect.poll(viewport).toEqual({ width: 820, height: 1430 })
  const box = (await corner.boundingBox())!
  await page.mouse.move(box.x + 10, box.y + 10)
  await page.mouse.down()
  await page.mouse.move(box.x - 20, box.y - 20, { steps: 4 })
  await expect.poll(async () => (await viewport()).height).toBeLessThan(1430)
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect.poll(viewport).toEqual({ width: 820, height: 1430 })
  await page.reload()
  await expect.poll(viewport).toEqual({ width: 820, height: 1430 })
  await page.setViewportSize({ width: 390, height: 844 })
  await choose(page, 'Preview width', 'Mobile S')
  await expect.poll(viewport).toEqual({ width: 320, height: 568 })
  await choose(page, 'Preview width', 'Auto')
  await expect(page.locator('.viewport-handle')).toHaveCount(0)
  await choose(page, 'Preview width', 'Custom')
  await expect.poll(viewport).toEqual({ width: 320, height: 568 })
})

test('saved brand management renames duplicates and deletes only confirmed local copies', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await projectAction(page, 'New brand')
  await projectAction(page, 'Manage brands')
  const manager = page.getByRole('dialog', { name: /^(Manage brands|Rename brand|Delete brand)$/ })
  await manager.getByRole('button', { name: /^Actions for/ }).click()
  await page.getByRole('menuitem', { name: 'Rename', exact: true }).click()
  await manager.getByLabel('Rename brand', { exact: true }).fill('Managed brand')
  await manager.getByRole('button', { name: 'Save name' }).click()
  await expect(manager.locator('li')).toContainText('Managed brand')
  await manager.getByRole('button', { name: /^Actions for/ }).click()
  await page.getByRole('menuitem', { name: 'Duplicate', exact: true }).click()
  const duplicate = page.getByRole('dialog', { name: 'Duplicate brand', exact: true })
  await duplicate.getByRole('button', { name: 'Create brand', exact: true }).click()
  await projectAction(page, 'Manage brands')
  await expect(manager.locator('li')).toHaveCount(2)
  await manager.getByLabel('Search saved brands').fill('Managed brand copy')
  await expect(manager.locator('li')).toHaveCount(1)
  await manager.getByRole('button', { name: /^Actions for/ }).click()
  await page.getByRole('menuitem', { name: 'Delete local copy' }).click()
  await manager.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(manager.locator('li')).toHaveCount(1)
  await manager.getByRole('button', { name: /^Actions for/ }).click()
  await page.getByRole('menuitem', { name: 'Delete local copy' }).click()
  await manager.getByRole('button', { name: 'Delete local copy' }).click()
  await expect(manager.getByText('No matching brands', { exact: true })).toBeVisible()
  await manager.getByLabel('Search saved brands').fill('')
  await expect(manager.locator('li')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/studio-manage-brands.png', animations: 'disabled' })
  await page.reload()
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await projectAction(page, 'Manage brands')
  await expect(manager.locator('li')).toHaveCount(1)
  await expect(manager.locator('li')).toContainText('Managed brand')
})

test('brand editing isolates previews and supports undo, redo, reset and real states', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await setCompare(page, true)
  const original = page.frameLocator('iframe[title="Original brand preview"]')
  await openPanel(page, 'Brand')
  await page.getByLabel('Brand name', { exact: true }).fill('A considered revision')
  await page.getByLabel('Brand name', { exact: true }).press('Tab')
  await closeEditor(page)
  await page.getByRole('button', { name: 'Undo change' }).click()
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText(source.theme.label)
  await page.getByRole('button', { name: 'Redo change' }).click()
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('A considered revision')
  await surfaces(page)
  await page.getByLabel('Page background', { exact: true }).fill('#e0f2fe')
  await page.getByLabel('Page background', { exact: true }).press('Tab')
  await expect(draft(page).locator('body')).toHaveCSS('background-color', 'rgb(224, 242, 254)')
  await expect(original.locator('body')).not.toHaveCSS('background-color', 'rgb(224, 242, 254)')
  await setMode(page, 'Dark')
  await expect(draft(page).locator('html')).toHaveClass(/dark/)
  await expect(original.locator('html')).toHaveClass(/dark/)
  await previewSettings(page)
  await choose(page, 'Preview state', 'Validation error')
  await page.keyboard.press('Escape')
  await expect(draft(page).getByText('Enter a valid email address.')).toBeVisible()
  await draft(page).getByRole('textbox', { name: 'Your email' }).fill('draft@example.com')
  await expect(original.getByRole('textbox', { name: 'Your email' })).toHaveValue('')
  await projectAction(page, 'Reset draft')
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('A considered revision')
  await expect(page.getByRole('button', { name: 'Undo change' })).toBeEnabled()
  await expect(page.getByRole('button', { name: 'Redo change' })).toBeDisabled()
})

test('source export preserves the complete brand and invalid imports leave it intact', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await page.getByLabel('Open brand document').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"version":2}') })
  await expect(page.getByRole('region', { name: 'Notifications (F8)' }).getByRole('listitem')).toHaveCount(1)
  await projectAction(page, 'Review changes')
  const tabs = page.getByRole('dialog').getByRole('tablist')
  const panel = page.getByRole('tabpanel')
  await expect(panel).toBeVisible()
  const dialog = page.getByRole('dialog')
  expect(await dialog.evaluate(element => element.clientHeight)).toBeLessThan(720)
  expect((await panel.boundingBox())!.y).toBeGreaterThan((await tabs.boundingBox())!.y)
  await page.getByRole('tab', { name: 'Code', exact: true }).click()
  await expect(panel.locator('pre')).toContainText('"version"')
  expect(await dialog.evaluate(element => element.clientHeight)).toBeLessThanOrEqual((page.viewportSize()?.height || 1000) - 32)
  await choose(page, 'Code format', 'CSS')
  await expect(panel.locator('pre')).toContainText('--ui-')
  expect(await dialog.evaluate(element => element.clientHeight)).toBeLessThanOrEqual((page.viewportSize()?.height || 1000) - 32)
  await page.getByRole('tab', { name: 'Changes', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('tab', { name: 'Export', exact: true }).click()
  await page.getByRole('button', { name: 'Download JSON' }).click()
  const download = await downloadPromise
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  expect(JSON.parse(Buffer.concat(chunks).toString())).toEqual(source)
  const archivePromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download ZIP' }).click()
  const archive = await archivePromise
  expect(archive.suggestedFilename()).toMatch(/\.zip$/)
  await archive.saveAs('test-results/exported-brand.zip')
})

test('new brands clear inherited styles and keep a recoverable local draft', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await projectAction(page, 'New brand')
  await openPanel(page, 'Brand')
  await expect(page.locator('.studio-project-name').filter({ hasText: 'New brand' })).toBeVisible()
  await expect(draft(page).locator('body')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await expect(draft(page).getByRole('img', { name: /happydesigns/ })).toHaveCount(0)
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('My saved draft')
  await page.getByLabel(/^Brand name/).press('Tab')
  page.on('dialog', dialog => dialog.accept())
  await page.reload()
  await expect(page.getByRole('button', { name: 'Restore draft' })).toHaveCount(0)
  await expect(page.locator('.studio-project-name').filter({ hasText: 'My saved draft' })).toBeVisible()
  await choose(page, 'Template', 'Landing')
  await expect(draft(page).getByRole('heading', { name: 'Your projects, in one place' })).toBeVisible()
  await choose(page, 'Template', 'Docs')
  await expect(draft(page).getByRole('heading', { level: 1 })).toBeVisible({ timeout: 30_000 })
})

// Independent iframe UApp regions have the same upstream notification label.
test('studio shell and component scene have no new semantic accessibility violations', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await page.screenshot({ path: 'test-results/studio-desktop.png', fullPage: true, animations: 'disabled' })
  const result = await new AxeBuilder({ page }).disableRules(['landmark-unique']).analyze()
  expect(result.violations).toEqual([])
  await setMode(page, 'Dark')
  await expect(draft(page).locator('html')).toHaveCSS('color-scheme', 'dark')
  const dark = await new AxeBuilder({ page }).disableRules(['landmark-unique']).analyze()
  expect(dark.violations).toEqual([])
})

test('@mobile studio keeps controls and preview inside the viewport', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await openPanel(page, 'Palette')
  await expect(page.getByRole('button', { name: 'Primary', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/studio-mobile.png', fullPage: true, animations: 'disabled' })
})

for (const viewport of [{ width: 1716, height: 1300 }, { width: 1440, height: 900 }, { width: 1024, height: 600 }, { width: 768, height: 600 }]) {
  test(`preview owns scrolling at ${viewport.width} × ${viewport.height}`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await page.goto('/studio?browse=true')
    await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
    const geometry = await page.evaluate(() => {
      const frame = document.querySelector<HTMLIFrameElement>('iframe')!
      const rect = frame.getBoundingClientRect()
      const doc = frame.contentDocument!
      const cards = [...doc.querySelectorAll('[data-example]')].map(card => card.getBoundingClientRect())
      return {
        outerHeight: document.documentElement.scrollHeight,
        outerWidth: document.documentElement.scrollWidth,
        previewHeight: rect.height,
        frameWidth: frame.clientWidth,
        contentWidth: doc.documentElement.scrollWidth,
        contentHeight: doc.querySelector('.component-gallery')!.scrollHeight,
        visibleCards: cards.filter(card => card.top < rect.height && card.bottom > 0).length,
        columns: new Set(cards.map(card => Math.round(card.left))).size
      }
    })
    expect(geometry.outerHeight).toBe(viewport.height)
    expect(geometry.outerWidth).toBe(viewport.width)
    expect(geometry.previewHeight).toBeGreaterThan(viewport.height * 0.68)
    expect(geometry.contentWidth).toBeLessThanOrEqual(geometry.frameWidth)
    expect(geometry.contentHeight).toBeGreaterThan(geometry.previewHeight)
    expect(geometry.visibleCards).toBeGreaterThanOrEqual(viewport.width >= 1440 ? 4 : 2)
    expect(geometry.columns).toBe(viewport.width >= 1440 ? 4 : viewport.width >= 1024 ? 3 : 2)
    const box = await page.locator('iframe').boundingBox()
    await page.mouse.move(box!.x + 30, box!.y + 100)
    await page.mouse.wheel(0, 650)
    await expect.poll(() => draft(page).locator('.component-gallery').evaluate(element => element.scrollTop)).toBeGreaterThan(0)
    expect(await page.evaluate(() => window.scrollY)).toBe(0)
    await expect(page.getByRole('button', { name: 'Preview settings', exact: true })).toBeInViewport()
    await openPanel(page, 'Palette')
    await expect(page.locator('#studio-editor')).toBeInViewport()
    await page.getByRole('button', { name: 'Close settings' }).click()
    await expect(page.locator('#studio-editor')).toHaveCount(0)
    await setMode(page, 'Dark')
    await expect(draft(page).locator('html')).toHaveCSS('color-scheme', 'dark')
    await draft(page).locator('.component-gallery').evaluate(element => element.scrollTo(0, 0))
    await expect.poll(() => draft(page).locator('.component-gallery').evaluate(element => element.scrollTop)).toBe(0)
    await page.screenshot({ path: `test-results/studio-${viewport.width}-${viewport.height}.png`, animations: 'disabled' })
  })
}

test('@mobile preview and settings remain independently reachable without page scrolling', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await openPanel(page, 'Palette')
  await expect(page.getByRole('button', { name: 'Primary', exact: true })).toBeVisible()
  await closeEditor(page)
  await draft(page).getByRole('textbox', { name: 'Your email' }).fill('mobile@example.com')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toHaveValue('mobile@example.com')
  await setCompare(page, true)
  for (const frame of await page.locator('iframe').all()) await expect(frame).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBe(await page.evaluate(() => innerHeight))
  await setCompare(page, false)
})

test('@mobile Booking template fits the preview and follows dark mode', async ({ page }) => {
  await page.goto('/studio?browse=true&view=booking&mode=dark')
  await expect(draft(page).getByRole('heading', { name: 'Find your next experience' })).toBeVisible({ timeout: 30000 })
  expect(await draft(page).locator('html').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await expect(draft(page).locator('html')).toHaveClass(/dark/)
  await page.screenshot({ path: 'test-results/studio-booking-mobile.png', animations: 'disabled' })
  expect((await new AxeBuilder({ page }).disableRules(['landmark-unique']).analyze()).violations).toEqual([])
})

test('Booking template navigates real components without creating a reservation', async ({ page }) => {
  await page.goto('/studio?browse=true&view=booking')
  await expect(draft(page).getByRole('heading', { name: 'Find your next experience' })).toBeVisible({ timeout: 30000 })
  await page.screenshot({ path: 'test-results/studio-booking.png', animations: 'disabled' })
  await draft(page).getByRole('button', { name: 'Photography walk', exact: true }).click()
  await expect(page).toHaveURL(/view=booking/)
  await expect(page).toHaveURL(/page=summary/)
  await expect(draft(page).getByRole('heading', { name: 'Photography walk', exact: true })).toBeVisible()
  await setCompare(page, true)
  await expect(page.frameLocator('iframe[title="Original brand preview"]').getByRole('heading', { name: 'Design workshop', exact: true })).toBeVisible()
  await draft(page).getByRole('button', { name: 'Back to sessions' }).click()
  await expect(page).toHaveURL(/page=home/)
  expect(await page.evaluate(() => Object.keys(localStorage).filter(key => /booking/i.test(key)))).toEqual([])
})

test('capability template shares real course navigation and isolates learner state', async ({ page }) => {
  test.setTimeout(90000)
  const firstLesson = '/courses/abap-platform-rap120/getting-started'
  await page.goto(firstLesson)
  // The standalone page is server-rendered; retry the idempotent action until
  // hydration has attached the checkpoint's event handler.
  await expect(async () => {
    await page.getByRole('checkbox').first().check()
  }).toPass({ timeout: 15000 })
  await page.getByRole('textbox', { name: 'Group ID', exact: true }).fill('ABC')
  await page.getByRole('textbox', { name: 'Group ID', exact: true }).press('Tab')
  await page.reload()
  await expect(page.getByRole('checkbox').first()).toBeChecked()
  await expect(page.getByRole('textbox', { name: 'Group ID', exact: true })).toHaveValue('ABC')
  const savedProgress = await page.evaluate(() => Object.fromEntries(Object.entries(localStorage).filter(([key]) => key.startsWith('course'))))
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await choose(page, 'Template', 'Course')
  await expect(draft(page).getByRole('heading', { name: 'Courses', exact: true })).toBeVisible({ timeout: 30000 })
  await expect(draft(page).locator('html')).toHaveAttribute('data-id-preview', 'ready', { timeout: 30000 })
  await expect(draft(page).getByRole('banner')).toHaveCount(1)
  await page.screenshot({ path: 'test-results/studio-course-home.png', animations: 'disabled' })
  expect((await new AxeBuilder({ page }).disableRules(['landmark-unique']).analyze()).violations).toEqual([])
  await draft(page).getByRole('link', { name: /RAP120 - Build SAP Fiori Apps/ }).click()
  await expect.poll(() => new URL(page.url()).searchParams.get('path')).toBe('/courses/abap-platform-rap120')
  await expect(draft(page).getByRole('heading', { name: 'RAP120 - Build SAP Fiori Apps with ABAP Cloud and SAP Joule for Developers', exact: true })).toBeVisible()
  await setCompare(page, true)
  const original = page.frameLocator('iframe[title="Original brand preview"]')
  await lesson(page)
  await expect(draft(page).getByRole('heading', { name: 'Getting Started', exact: true })).toBeVisible({ timeout: 30000 })
  await expect(original.getByRole('heading', { name: 'Getting Started', exact: true })).toBeVisible({ timeout: 30000 })
  const checkpoint = draft(page).getByRole('checkbox').first()
  await expect(checkpoint).not.toBeChecked()
  await expect(draft(page).getByRole('textbox', { name: 'Group ID', exact: true })).toHaveValue('')
  await checkpoint.check()
  await draft(page).getByRole('textbox', { name: 'Group ID', exact: true }).fill('XYZ')
  await draft(page).getByRole('textbox', { name: 'Group ID', exact: true }).press('Tab')
  await expect(checkpoint).toBeChecked()
  await expect(original.getByRole('checkbox').first()).not.toBeChecked()
  await setMode(page, 'Dark')
  await expect(checkpoint).toBeChecked()
  await expect(draft(page).locator('html')).toHaveClass(/dark/)
  await draft(page).getByRole('link', { name: 'Course home', exact: true }).click()
  await lesson(page)
  await expect(checkpoint).toBeChecked()
  await expect(draft(page).getByRole('textbox', { name: 'Group ID', exact: true })).toHaveValue('XYZ')
  await expect(original.getByRole('checkbox').first()).not.toBeChecked()
  await expect(original.getByRole('textbox', { name: 'Group ID', exact: true })).toHaveValue('')
  expect(await page.evaluate(() => Object.fromEntries(Object.entries(localStorage).filter(([key]) => key.startsWith('course'))))).toEqual(savedProgress)
  await page.screenshot({ path: 'test-results/studio-course-compare.png', animations: 'disabled' })
})

test('@mobile capability template stays usable within the studio viewport', async ({ page }) => {
  await page.goto('/studio?browse=true&view=course')
  await expect(draft(page).getByRole('heading', { name: 'Courses', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await draft(page).locator('html').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/studio-course-mobile.png', animations: 'disabled' })
  await lesson(page)
  await expect(draft(page).getByRole('heading', { name: 'Getting Started', exact: true })).toBeVisible({ timeout: 30000 })
  expect(await draft(page).locator('html').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})

test('Course template exposes the real project workspace', async ({ page }) => {
  await page.goto('/studio?browse=true&view=course&path=/courses/abap-platform-rap120/generate-application')
  await expect(draft(page).getByRole('heading', { name: 'Generate the Travel Application', exact: true })).toBeVisible({ timeout: 30000 })
  await expect(draft(page).locator('html')).toHaveAttribute('data-id-preview', 'ready', { timeout: 30000 })
  const workspace = draft(page).getByRole('navigation', { name: 'Project files', exact: true })
  await expect(workspace).toBeVisible()
  await draft(page).locator('.course-reader pre').first().scrollIntoViewIfNeeded()
  await expect(workspace.getByRole('tree')).toBeVisible()
  await expect(workspace.locator('pre')).toContainText(/.+/)
  await page.screenshot({ path: 'test-results/studio-course-workspace.png', animations: 'disabled' })
})

test('production loads capability scene only when selected', async ({ page }, testInfo) => {
  test.skip(process.env.STUDIO_PRODUCTION !== 'true', 'Run against the production build with STUDIO_PRODUCTION=true.')
  const buildDir = process.env.HD_DOCS_BUILD_DIR ? resolve('docs', process.env.HD_DOCS_BUILD_DIR) : resolve('docs/node_modules/.cache/nuxt/.nuxt')
  const client = resolve(buildDir, 'dist/client')
  const manifest = (await import(pathToFileURL(resolve(client, '../server/client.manifest.mjs')).href)).default as Record<string, { file: string }>
  const scene = Object.entries(manifest).find(([key]) => key.replaceAll('\\', '/').includes('preview/app/pages/courses/index.vue'))?.[1]
  expect(scene, 'The capability must have its own production chunk').toBeTruthy()
  const requests: string[] = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  expect(requests.some(url => url.endsWith(scene!.file))).toBe(false)
  const before = requests.length
  const start = Date.now()
  await choose(page, 'Template', 'Course')
  await expect(draft(page).getByRole('heading', { name: 'Courses', exact: true })).toBeVisible()
  expect(requests.some(url => url.endsWith(scene!.file))).toBe(true)
  const module = readFileSync(resolve(client, '_nuxt', scene!.file))
  const report = { sceneChunk: scene!.file, sceneBytes: module.length, sceneGzipBytes: gzipSync(module).length, selectionToVisibleMs: Date.now() - start, initialRequestCount: before, additionalRequests: requests.slice(before) }
  const reportPath = testInfo.outputPath('course-loading.json')
  writeFileSync(reportPath, JSON.stringify(report, null, 2))
  await testInfo.attach('course-loading.json', { path: reportPath, contentType: 'application/json' })
})

test('feedback validates real fields and template controls stay relevant', async ({ page }) => {
  await page.goto('/studio?browse=true')
  const frame = draft(page)
  await expect(frame.getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await previewSettings(page)
  await choose(page, 'Preview state', 'Validation error')
  await page.keyboard.press('Escape')
  await expect(frame.getByText('Enter a valid email address.')).toBeVisible()
  await choose(page, 'Template', 'Landing')
  await previewSettings(page)
  await expect(page.getByRole('combobox', { name: 'Preview state' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await frame.getByRole('button', { name: 'Create a project', exact: true }).click()
  await frame.getByRole('textbox', { name: 'Project name', exact: true }).fill('Website redesign')
  await frame.getByRole('button', { name: 'Create project', exact: true }).click()
  await expect(frame.getByText('Project created', { exact: true })).toBeVisible()
})

test('@mobile header keeps project actions secondary and keyboard accessible', async ({ page }) => {
  await page.goto('/studio?browse=true&view=course')
  await expect(draft(page).getByRole('heading', { name: 'Courses', exact: true })).toBeVisible()
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 })
    expect((await page.locator('.studio-header').boundingBox())!.height).toBeLessThanOrEqual(110)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByRole('button', { name: 'Export', exact: true })).toBeVisible()
  }
  await page.getByRole('button', { name: 'Export', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog', { name: 'Export brand' })).toBeVisible()
  await page.keyboard.press('Escape')
  await brandActions(page)
  const fileChooser = page.waitForEvent('filechooser')
  await page.getByRole('menuitem', { name: 'Import brand', exact: true }).click()
  await fileChooser
  await projectAction(page, 'New brand')
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('New brand')
})

test('projects survive switching and export preserves the comparison baseline', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Project A')
  await page.getByLabel(/^Brand name/).press('Tab')
  await expect.poll(() => page.evaluate(() => Object.keys(localStorage).filter(key => key.startsWith('id-studio:project:2:')).length)).toBeGreaterThan(0)
  await projectAction(page, 'Review changes')
  const downloading = page.waitForEvent('download')
  await page.getByRole('tab', { name: 'Export', exact: true }).click()
  await page.getByRole('button', { name: 'Download JSON' }).click()
  await downloading
  await expect(page.getByRole('button', { name: 'Download JSON', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await projectAction(page, 'New brand')
  await openPanel(page, 'Brand')
  await expect(page.getByRole('dialog', { name: 'Replace this draft?' })).toHaveCount(0)
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Project B')
  await page.getByLabel(/^Brand name/).press('Tab')
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('menuitem', { name: /^Project A(?: |$)/ }).click()
  await expect(page.getByRole('dialog', { name: 'Replace this draft?' })).toHaveCount(0)
  await expect(page.locator('.studio-project-name').filter({ hasText: 'Project A' })).toBeVisible()
  await brandActions(page)
  await expect(page.getByRole('menuitem', { name: 'Reset appearance…', exact: true })).toBeEnabled()
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Restore draft' })).toHaveCount(0)
  await expect(page.locator('.studio-project-name').filter({ hasText: 'Project A' })).toBeVisible()
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: /^Project B(?: |$)/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await projectAction(page, 'Reset draft')
  await expect(page.locator('.studio-project-name').filter({ hasText: 'Project A' })).toBeVisible()
})

test('view URLs restore safe navigation state without including draft data', async ({ page }) => {
  await page.goto('/studio?browse=true&view=course&path=/courses/abap-platform-rap120/getting-started&mode=dark&compare=true')
  await expect(draft(page).getByRole('heading', { name: 'Getting Started', exact: true })).toBeVisible({ timeout: 30000 })
  await expect(draft(page).locator('html')).toHaveClass(/dark/)
  await expect(page.locator('iframe')).toHaveCount(2)
  await draft(page).getByRole('link', { name: 'Course home', exact: true }).click()
  await expect.poll(() => new URL(page.url()).searchParams.get('path')).toBe('/courses')
  await page.reload()
  await expect(draft(page).getByRole('heading', { name: 'Courses', exact: true })).toBeVisible()
  expect(page.url()).not.toContain('brand.studio')
  await page.goto('/studio?browse=true&view=invalid&page=bad&mode=invalid')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await expect(draft(page).locator('html')).toHaveClass(/light/)
})

test('brand picker isolates brands, preserves drafts and protects the Nuxt UI baseline', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Studio library draft')
  await page.getByLabel(/^Brand name/).press('Tab')
  const shellColor = await page.locator('.studio-shell').evaluate(element => getComputedStyle(element).backgroundColor)
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('menuitem', { name: /^Nuxt UI(?: |$)/ }).click()
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('Nuxt UI')
  await expect(page.locator('#studio-editor')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Create brand', exact: true })).toBeVisible()
  await expect(page.locator('.studio-shell')).toHaveCSS('background-color', shellColor)
  await page.getByRole('button', { name: 'Brand picker' }).click()
  await page.getByLabel('Search brands', { exact: true }).fill('library')
  await page.getByRole('menuitem', { name: /^Studio library draft(?: |$)/ }).click()
  await openPanel(page, 'Brand')
  await expect(page.getByLabel(/^Brand name/)).toHaveValue('Studio library draft')
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('menuitem', { name: /^Nuxt UI(?: |$)/ }).click()
  await page.getByRole('button', { name: 'Create brand', exact: true }).click()
  await nameBrand(page)
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Independent brand')
  await page.getByLabel(/^Brand name/).press('Tab')
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('menuitem', { name: /^Nuxt UI(?: |$)/ }).click()
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('Nuxt UI')
  await page.getByRole('button', { name: 'Brand picker', exact: true }).click()
  await page.getByRole('menuitem', { name: /^Independent brand(?: |$)/ }).click()
  await openPanel(page, 'Brand')
  await expect(page.getByLabel(/^Brand name/)).toHaveValue('Independent brand')
  await page.getByRole('button', { name: 'Brand picker' }).click()
  await expect(page.getByRole('option', { name: 'Create new brand', exact: true })).toHaveCount(0)
  await expect(page.getByRole('option', { name: 'Download', exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/studio-brand-library.png', animations: 'disabled' })
})

test('visual authoring validates fields and previews palette, fonts and contrast', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await openPanel(page, 'Palette')
  await page.getByRole('button', { name: 'Neutral', exact: true }).click()
  const neutrals = page.getByLabel('Neutral palettes', { exact: true })
  await expect(neutrals.getByRole('button', { name: 'slate', exact: true })).toBeVisible()
  await expect(neutrals.getByRole('button', { name: 'green', exact: true })).toHaveCount(0)
  await expect(neutrals.getByRole('button', { name: 'sand', exact: true })).toBeVisible()
  await neutrals.getByRole('button', { name: 'Show all palettes', exact: true }).click()
  await expect(neutrals.getByRole('button', { name: 'green', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('iframe[title="Draft brand preview"]')).toHaveCSS('box-shadow', 'none')
  await expect(page.locator('.viewport-clip')).toHaveCSS('overflow', 'hidden')

  await page.getByRole('button', { name: 'New palette', exact: true }).click()
  await page.getByRole('dialog', { name: 'New palette', exact: true }).getByLabel('Palette name').fill('accent')
  await page.getByRole('textbox', { name: 'Base color', exact: true }).fill('#d946ef')
  await page.getByRole('textbox', { name: 'Base color', exact: true }).press('Tab')
  await page.getByRole('button', { name: 'Create palette', exact: true }).click()
  await page.getByRole('button', { name: 'Primary', exact: true }).click()
  const palettes = page.getByLabel('Primary palettes', { exact: true })
  for (const name of ['emerald', 'yellow', 'accent']) {
    await expect(palettes.getByRole('button', { name, exact: true }).locator('span').first()).not.toHaveCSS('background-image', 'none')
  }
  await page.screenshot({ path: 'test-results/studio-color-grid.png', animations: 'disabled' })
  await palettes.getByRole('button', { name: 'accent', exact: true }).click()
  await expect(palettes).toBeHidden()
  await expect(page.getByRole('button', { name: /^accent/, expanded: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'accent 500', exact: true })).toHaveValue('#d946ef')
  await page.getByRole('button', { name: 'Choose color for accent 500' }).click()
  await expect(page.getByRole('button', { name: 'Apply color', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Apply color', exact: true }).click()
  await page.screenshot({ path: 'test-results/studio-palette-editor.png', animations: 'disabled' })
  await openPanel(page, 'Typography')
  await choose(page, 'Body', 'System serif')
  await expect(page.getByText('The quick brown fox. 0123456789').first()).toHaveCSS('font-family', 'Georgia, serif')
  await openPanel(page, 'Appearance')
  await choose(page, 'Corner radius', '0.5rem')
  await expect(page.getByLabel('Corner radius', { exact: true })).toHaveValue('0.5rem')
  await surfaces(page)
  const background = page.getByRole('textbox', { name: 'Page background', exact: true })
  await background.fill('not-a-color')
  await background.press('Tab')
  await expect(page.getByText('Enter a valid CSS color.', { exact: true })).toBeVisible()
  await expect(background).toHaveAttribute('aria-invalid', 'true')
  await background.fill('#ffffff')
  await background.press('Tab')
  await expect(page.getByText('Enter a valid CSS color.', { exact: true })).toHaveCount(0)
  const text = page.getByRole('textbox', { name: 'Body text', exact: true })
  await text.fill('#eeeeee')
  await text.press('Tab')
  await expect(page.getByText(/below 4.5:1 for normal text/)).toBeVisible()
})

test('storage failures protect edits until an export is downloaded', async ({ page }) => {
  await page.addInitScript(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key.startsWith('id-studio:')) throw new DOMException('Quota exceeded', 'QuotaExceededError')
      return original.call(this, key, value)
    }
  })
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await openPanel(page, 'Brand')
  await page.getByLabel(/^Brand name/).fill('Keep these edits')
  await page.getByLabel(/^Brand name/).press('Tab')
  await expect(page.getByText('Local draft storage is unavailable. Export your source before leaving.', { exact: true })).toBeVisible()
  await projectAction(page, 'New brand')
  await expect(page.getByRole('dialog', { name: 'Replace this draft?' })).toBeVisible()
  await page.getByRole('button', { name: 'Keep editing', exact: true }).click()
  await projectAction(page, 'Review changes')
  const download = page.waitForEvent('download')
  await page.getByRole('tab', { name: 'Export', exact: true }).click()
  await page.getByRole('button', { name: 'Download JSON', exact: true }).click()
  await download
  await page.keyboard.press('Escape')
  await projectAction(page, 'New brand')
  await openPanel(page, 'Brand')
  await expect(page.locator('.studio-project-name').filter({ hasText: 'New brand' })).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Replace this draft?' })).toHaveCount(0)
})

test('creating a brand requires a distinct name and browsing creates no saved copies', async ({ page }) => {
  await page.goto('/studio?browse=true&mode=light')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  const savedCount = () => page.evaluate(() => Object.keys(localStorage).filter(key => key.startsWith('id-studio:project:2:')).length)
  expect(await savedCount()).toBe(0)
  await brandActions(page)
  await page.getByRole('menuitem', { name: 'Create new brand', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Create brand', exact: true })
  await expect(dialog.getByRole('button', { name: 'Create brand', exact: true })).toBeDisabled()
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect(await savedCount()).toBe(0)
  await page.getByRole('button', { name: 'Brand picker' }).click()
  await page.getByRole('menuitem', { name: /^Nuxt UI(?: |$)/ }).click()
  expect(await savedCount()).toBe(0)
  await page.getByRole('button', { name: 'Create brand', exact: true }).click()
  await dialog.getByLabel('New brand name', { exact: true }).fill('Nuxt UI')
  await dialog.getByRole('button', { name: 'Create brand', exact: true }).click()
  await expect(dialog.getByText('A brand with this name already exists. Choose a different name.')).toBeVisible()
  await dialog.getByLabel('New brand name', { exact: true }).fill('A named brand')
  await dialog.getByRole('button', { name: 'Create brand', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText('A named brand')
  expect(await savedCount()).toBe(1)
  await page.evaluate((document) => {
    document.theme.label = 'New brand'
    for (const [id, updatedAt] of [['old-a', 1700000000000], ['old-b', 1700003600000]] as const) {
      localStorage.setItem(`id-studio:project:2:${id}`, JSON.stringify({ id, baseline: document, draft: document, updatedAt }))
    }
  }, structuredClone(source))
  await page.reload()
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await page.getByRole('button', { name: 'Brand picker' }).click()
  const legacy = page.getByRole('menuitem', { name: /^New brand / })
  await expect(legacy).toHaveCount(2)
  await page.keyboard.press('Escape')
  await projectAction(page, 'Manage brands')
  await expect(page.getByRole('dialog', { name: 'Manage brands' }).locator('time')).toHaveCount(3)
  await page.screenshot({ path: 'test-results/studio-named-brands.png', animations: 'disabled' })
})

test('inspector uses progressive controls and preserves explicit browse mode', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await expect(page.locator('#studio-editor')).toHaveCount(0)
  await openPanel(page, 'Brand')
  await expect(page.getByLabel('Identifier', { exact: true })).toHaveCount(0)
  await page.getByLabel('Brand name', { exact: true }).fill('Nuxt UI')
  await page.getByLabel('Brand name', { exact: true }).press('Tab')
  await expect(page.getByText('A brand with this name already exists.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Brand picker' })).not.toHaveText('Nuxt UI')
  await openPanel(page, 'Palette')
  await expect(page.getByRole('dialog', { name: 'New palette' })).toHaveCount(0)
  await page.getByRole('button', { name: 'New palette', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'New palette' }).getByLabel('Palette name')).toHaveValue('')
  await page.getByRole('dialog', { name: 'New palette' }).getByRole('button', { name: 'Cancel' }).click()
  await openPanel(page, 'Typography')
  await expect(page.getByRole('combobox', { name: 'Body', exact: true })).toBeVisible()
  await expect(page.getByLabel('Sans font stack')).toHaveCount(0)
  await closeEditor(page)
  await expect(page).toHaveURL(/browse=true/)
  await page.reload()
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await expect(page.locator('#studio-editor')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/studio-clean-desktop.png', animations: 'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await projectAction(page, 'Download')
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: 'Download JSON' })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Download ZIP' })).toBeVisible()
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await expect(dialog).toHaveCSS('opacity', '1')
  await page.screenshot({ path: 'test-results/studio-clean-download-mobile.png', animations: 'disabled' })
})

test('header positions stay fixed across template and brand labels', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 })
    const geometry = () => page.locator('.studio-header').evaluate(header => [...header.querySelectorAll('[aria-label="Brand picker"], [aria-label="Templates"], .studio-review')].map((element) => {
      const { x, y, width, height } = element.getBoundingClientRect()
      return { x, y, width, height }
    }))
    const before = await geometry()
    for (const template of ['Landing', 'Docs', 'Components']) {
      await choose(page, 'Template', template)
      await expect.poll(geometry).toEqual(before)
    }
    const brandDocument = structuredClone(source)
    brandDocument.theme.label = width === 1440 ? 'A considerably longer saved brand name' : 'Short'
    await page.getByLabel('Open brand document').setInputFiles({ name: 'brand.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(brandDocument)) })
    await expect(page.getByRole('button', { name: 'Brand picker' })).toHaveText(brandDocument.theme.label)
    await expect.poll(geometry).toEqual(before)
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
  }
})

test('palette lifecycle separates creation from assignment and preserves roles', async ({ page }) => {
  await page.goto('/studio?browse=true')
  await expect(draft(page).getByRole('textbox', { name: 'Your email' })).toBeVisible({ timeout: 30000 })
  await openPanel(page, 'Palette')
  await page.getByRole('button', { name: 'New palette', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'New palette', exact: true })
  await expect(dialog.getByLabel('Palette name')).toHaveValue('')
  await expect(dialog.getByRole('button', { name: 'Create palette' })).toBeDisabled()
  await dialog.getByLabel('Palette name').fill('green')
  await expect(dialog.getByRole('button', { name: 'Create palette' })).toBeDisabled()
  await dialog.getByLabel('Palette name').fill('ocean')
  await page.screenshot({ path: 'test-results/studio-create-palette.png', animations: 'disabled' })
  await dialog.getByRole('button', { name: 'Create palette' }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('button', { name: 'Primary', exact: true })).not.toContainText('Ocean')
  await page.getByRole('button', { name: 'Primary', exact: true }).click()
  await page.getByLabel('Primary palettes', { exact: true }).getByRole('button', { name: 'ocean', exact: true }).click()
  await page.getByRole('button', { name: 'Actions for palette ocean', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Rename', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Rename palette', exact: true })
  await dialog.getByLabel('Palette name').fill('lagoon')
  await dialog.getByRole('button', { name: 'Save name' }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('button', { name: 'Primary', exact: true })).toContainText('lagoon', { ignoreCase: true })
  await page.getByRole('button', { name: 'Actions for palette lagoon', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Delete palette', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Delete palette', exact: true })
  await expect(dialog.getByRole('button', { name: 'Delete palette' })).toBeDisabled()
  await dialog.getByRole('combobox', { name: 'Replacement palette' }).click()
  await page.getByRole('option', { name: 'blue', exact: true }).click()
  await dialog.getByRole('button', { name: 'Delete palette' }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('button', { name: 'Primary', exact: true })).toContainText('blue', { ignoreCase: true })
  await page.getByRole('button', { name: 'New palette', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'New palette' }).getByLabel('Palette name')).toHaveValue('')
})
