import { test, expect } from '@playwright/test'

test('Studio native controls preserve editing and preview behavior', async ({ page }) => {
  test.setTimeout(90_000)
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/studio', { waitUntil: 'domcontentloaded' })
  const brand = page.getByRole('button', { name: 'Brand picker', exact: true })
  await brand.click()
  const manage = page.getByRole('menuitem', { name: 'Manage brand', exact: true })
  await manage.hover()
  const create = page.getByRole('menuitem', { name: 'Create new brand', exact: true })
  await expect(create).toBeVisible()
  await create.hover()
  await page.waitForTimeout(300)
  await expect(create).toBeVisible()
  await create.click()
  await page.getByRole('textbox', { name: 'New brand name' }).fill('Standardized')
  await page.getByRole('dialog').getByRole('button', { name: 'Create brand', exact: true }).click()
  const editor = page.locator('#studio-editor')
  await expect(editor).toBeVisible()
  const draft = page.locator('iframe[title="Draft brand preview"]')
  const frame = await draft.elementHandle().then(el => el.contentFrame())
  await expect(frame.getByRole('textbox', { name: 'Your email' })).toBeVisible()
  await frame.getByRole('textbox', { name: 'Your email' }).click()
  await expect(editor).toBeHidden()
  const dock = page.getByRole('group', { name: 'Edit brand', exact: true })
  await dock.getByRole('button', { name: 'Styles', exact: true }).click()
  await expect(editor).toBeVisible()
  const canvas = await draft.boundingBox()
  await editor.getByRole('combobox', { name: 'Corner radius' }).click()
  await page.getByRole('option', { name: '0.625rem', exact: true }).click()
  await expect(editor).toBeVisible()
  await dock.getByRole('button', { name: 'Icons', exact: true }).click()
  await expect(editor.getByRole('radio')).toHaveCount(9)
  const radio = editor.getByRole('radio', { name: /Bootstrap/ })
  await radio.check()
  await expect(radio).toBeChecked()
  await radio.press('ArrowDown', { delay: 100 })
  await expect(editor.getByRole('radio', { name: /Heroicons/ })).toBeChecked()
  expect((await draft.boundingBox()).width).toBe(canvas.width)
  await editor.getByRole('button', { name: 'Pin editor', exact: true }).click()
  await expect(page.locator('.studio-editor-docked')).toBeVisible()
  await frame.locator('body').click({ position: { x: 10, y: 10 } })
  await expect(editor).toBeVisible()
  await editor.getByRole('button', { name: 'Unpin editor', exact: true }).click()
  await expect(page.locator('.studio-editor-overlay')).toBeVisible()
  await editor.getByRole('button', { name: 'Close settings', exact: true }).click()
  await expect(editor).toHaveCount(0)
  await brand.click()
  await page.getByPlaceholder('Search brands…').fill('standard')
  await expect(page.getByRole('menuitem', { name: /Standardized/ })).toBeVisible()
  await expect(page.getByRole('menuitem', { name: /Nuxt UI/ })).toHaveCount(0)
  await expect(manage).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Preview settings', exact: true }).click()
  await page.getByRole('combobox', { name: 'Viewport size' }).click()
  await page.getByRole('option', { name: 'Mobile', exact: true }).click()
  const width = page.getByRole('spinbutton', { name: 'Viewport width' })
  await width.fill('500')
  await width.press('Tab')
  await expect(width).toHaveValue('500')
  await page.getByRole('button', { name: 'Rotate viewport' }).click()
  await expect(page.getByRole('spinbutton', { name: 'Viewport height' })).toHaveValue('500')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Randomizer options' }).click()
  await expect(page.getByRole('menuitemcheckbox')).toHaveCount(5)
  await page.keyboard.press('Escape')
  await dock.getByRole('button', { name: 'Styles', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(editor).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
