export const actionExampleNames = new Set([
  'action-hierarchy-pattern',
  'compact-metadata-pattern',
  'button',
  'badge',
  'chip',
  'field-group',
  'kbd',
  'tooltip',
])

export const formExampleNames = new Set([
  'form-pattern',
  'text-entry-pattern',
  'selection-pattern',
  'choice-pattern',
  'bounded-pattern',
  'advanced-inputs-pattern',
  'form',
  'form-field',
  'input',
  'textarea',
  'select',
  'select-menu',
  'input-menu',
  'input-number',
  'input-tags',
  'input-date',
  'input-time',
  'checkbox',
  'checkbox-group',
  'radio-group',
  'switch',
  'slider',
  'pin-input',
  'file-upload',
  'color-picker',
  'calendar',
  'listbox',
])

export const feedbackExampleNames = new Set([
  'alert',
  'banner',
  'progress',
  'skeleton',
  'toast',
  'empty',
  'icon',
  'feedback-system-pattern',
])
